// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDUc9tJ8efzE-Pw0AF5X14L0-_XP9kRUA0',
    appId: '1:8775464826:web:1af49054aee2981c8008c3',
    messagingSenderId: '8775464826',
    projectId: 'hobby-tracker-d0426',
    authDomain: 'hobby-tracker-d0426.firebaseapp.com',
    storageBucket: 'hobby-tracker-d0426.appspot.com',
    measurementId: 'G-BQEZMBLPFT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpqKauP0_RonzNIn9gv3ln-AZfboPiAIU',
    appId: '1:8775464826:android:b20437e01e9e67e18008c3',
    messagingSenderId: '8775464826',
    projectId: 'hobby-tracker-d0426',
    storageBucket: 'hobby-tracker-d0426.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAHtk5ytN-VEHzsRVgmS86t_3DoKJdzbPc',
    appId: '1:8775464826:ios:6f372b7efb80cfde8008c3',
    messagingSenderId: '8775464826',
    projectId: 'hobby-tracker-d0426',
    storageBucket: 'hobby-tracker-d0426.appspot.com',
    iosBundleId: 'com.example.hobbyTracker',
  );
}
